FROM golang:latest

RUN mkdir -p /go/src/github.com/zlyzol/tendermint-0.32.3/tools/tm-bench
WORKDIR /go/src/github.com/zlyzol/tendermint-0.32.3/tools/tm-bench

COPY Makefile /go/src/github.com/zlyzol/tendermint-0.32.3/tools/tm-bench/

RUN make get_tools

COPY . /go/src/github.com/zlyzol/tendermint-0.32.3/tools/tm-bench

